version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: tarefas-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_tarefas
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      # - ./data:/var/lib/mysql
      - ./server/database.sql:/docker-entrypoint-initdb.d/database.sql
